name: flame_game
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  flame: ^1.8.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_sequence_animation: ^4.0.0
  get: ^4.6.5
  get_storage: ^2.1.1
  just_audio: ^0.9.34
  supabase: ^1.9.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 
  assets:
    - assets/images/
    - assets/sounds/
    - .env