name: flame_game
description: Serious game.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  animated_flip_counter: ^0.2.6
  animated_text_kit: ^4.2.2
  build_runner: ^2.4.6
  circular_countdown_timer: ^0.2.3
  flame: ^1.8.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_sequence_animation: ^4.0.0
  flutter_tts: ^3.8.3
  get: ^4.6.5
  get_storage: ^2.1.1
  just_audio: ^0.9.34
  lottie: ^2.6.0
  mockito: ^5.4.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  supabase_flutter: ^1.10.24
  test: ^1.24.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 
  assets:
    - assets/images/
    - assets/sounds/
    - assets/animations/
    - .env